// ──── COGNITIVE DOMAIN METADATA ────
export const DOMAIN_META = [
  {
    id: "recall",
    label: "Recall Engine",
    emoji: "🧠",
    color: "cyan",
    description: "Active recall, long-term retention, learning speed, and memory reconstruction.",
    scienceBasis: "Retrieval practice produces a 'testing effect': recalling information from memory is significantly more effective for long-term retention than re-reading or re-studying. Variable retrieval (PNAS, 2024) boosts this further by slightly changing the context on each recall attempt.",
    transferTargets: ["Remembering protocols, names, and procedures", "Absorbing medical or study content faster", "Retaining conversations and instructions"],
    evidenceLevel: "strong" as const,
  },
  {
    id: "working_memory",
    label: "Working Memory Lab",
    emoji: "⚡",
    color: "purple",
    description: "Mental juggling, attentional control, rapid updating, and multi-task information holding.",
    scienceBasis: "Working memory training shows reliable near-transfer (Pahor et al., Nature Human Behaviour, 2022). Far transfer to fluid intelligence is more limited and depends on individual near-transfer gains. Tasks using real-world stimuli (medication orders, directions) show better ecological validity than abstract shapes.",
    transferTargets: ["Holding multiple variables in mind while problem-solving", "Following complex instructions without notes", "Tracking several things simultaneously under pressure"],
    evidenceLevel: "moderate" as const,
    caveat: "Far transfer from WM training is limited. Near transfer (similar tasks) is more reliable. Treat WM training as a tool for improving attentional strategies, not a magic 'intelligence boost'.",
  },
  {
    id: "focus",
    label: "Focus Chamber",
    emoji: "🎯",
    color: "green",
    description: "Sustained attention, selective attention, inhibitory control, and distractor resistance.",
    scienceBasis: "Inhibitory control — the ability to suppress irrelevant responses — is a core executive function that supports nearly all complex cognitive tasks. Go/no-go and Stroop-type tasks reliably train this. Serious games for attention show significant near-transfer effects (Frontiers, 2026).",
    transferTargets: ["Studying without getting distracted", "Resisting impulsive decisions under time pressure", "Maintaining precision in clinical or professional settings"],
    evidenceLevel: "moderate" as const,
  },
  {
    id: "flexibility",
    label: "Flexibility Arena",
    emoji: "🔄",
    color: "orange",
    description: "Task-switching, rule revision, perspective shifting, and adaptive responding.",
    scienceBasis: "Cognitive flexibility training through rule-shift paradigms and perspective-taking tasks shows near-transfer to new switching scenarios. Abrupt rule changes (rather than gradual) produce stronger training effects by forcing error detection and strategy revision.",
    transferTargets: ["Adapting when plans fail in real time", "Switching between different roles or contexts fluidly", "Handling ambiguous information without anchoring prematurely"],
    evidenceLevel: "moderate" as const,
  },
  {
    id: "problem_solving",
    label: "Problem-Solving Forge",
    emoji: "🔧",
    color: "blue",
    description: "Causal reasoning, systems thinking, hypothesis testing, and decision analysis.",
    scienceBasis: "Deliberate practice on constraint-solving problems, Fermi estimation, and structured decision-making frameworks produces measurable improvements in reasoning quality. Simulation-based training with feedback produces superior transfer compared to passive instruction.",
    transferTargets: ["Clinical judgment and differential diagnosis", "Emergency prioritization and resource allocation", "Business decisions, leadership, and troubleshooting"],
    evidenceLevel: "moderate" as const,
  },
  {
    id: "creativity",
    label: "Creativity Studio",
    emoji: "💡",
    color: "amber",
    description: "Divergent thinking, analogical reasoning, idea generation, and constraint-based innovation.",
    scienceBasis: "Creativity training using SCAMPER, constraint manipulation, and analogy generation has demonstrated improvements in divergent thinking scores (critical thinking education interventions, 2023). The divergent-to-convergent funnel model structures idea generation and filtering effectively.",
    transferTargets: ["Novel problem-solving when standard approaches fail", "Design thinking, writing, and strategy", "Innovation in clinical, business, or technical domains"],
    evidenceLevel: "moderate" as const,
  },
  {
    id: "intuition",
    label: "Intuition Lab",
    emoji: "🔮",
    color: "rose",
    description: "Calibrated intuition, probability estimation, forecasting, and pattern recognition.",
    scienceBasis: "Metacognitive calibration training (Seth & Lau, 2018) through adaptive feedback improves accuracy-confidence alignment across domains. Overconfidence is the most common bias and is reliably reduced with repeated calibration feedback. Fast-judgment tasks improve signal detection.",
    transferTargets: ["Reading clinical situations accurately without full data", "Risk assessment and decision-making under uncertainty", "Leadership judgment and situation awareness"],
    evidenceLevel: "moderate" as const,
  },
  {
    id: "metacognition",
    label: "Metacognition Console",
    emoji: "🪞",
    color: "teal",
    description: "Self-awareness, strategy selection, error pattern identification, and self-regulated learning.",
    scienceBasis: "Metacognitive monitoring — tracking your own performance and adjusting strategy — is one of the strongest predictors of learning outcomes. Prediction-then-feedback loops, error classification, and reflection journaling are all evidence-based metacognitive tools (Fleming et al., domain-general improvements in calibration).",
    transferTargets: ["Identifying your own cognitive failure modes", "Selecting the right mental strategy for a task", "Improving learning efficiency over time"],
    evidenceLevel: "strong" as const,
  },
];

// ──── TRAINING ACTIVITIES ────
export const ACTIVITIES = [
  // RECALL
  {
    id: "spaced-recall",
    domain: "recall",
    name: "Spaced Recall Drill",
    emoji: "📚",
    difficulty: "Adaptive",
    durationMin: 5,
    description: "Flashcard-style prompts with variable retrieval: same concept, different framing each time.",
    instructions: "You'll see a prompt. Try to recall the answer completely before revealing it. Then rate your recall quality from 0 (forgotten) to 5 (perfect). The algorithm adapts spacing accordingly.",
    transferNote: "Builds long-term retention of any content: medical protocols, study material, professional knowledge.",
    evidenceBasis: "SM-2 spaced repetition algorithm; variable retrieval effect (Butowska et al., PNAS 2024)",
    type: "recall-vault" as const,
  },
  {
    id: "explain-from-memory",
    domain: "recall",
    name: "Explain From Memory",
    emoji: "🗣️",
    difficulty: "Medium",
    durationMin: 3,
    description: "A concept is given. Explain it completely from memory without looking.",
    instructions: "Read the topic. Close your eyes for 10 seconds. Then type everything you know about it. Be specific: mechanisms, examples, edge cases. You rate your own completeness.",
    transferNote: "Forces deeper encoding than passive re-reading. Mirrors the 'teach it back' technique used by expert learners.",
    evidenceBasis: "The testing effect; elaborative interrogation; self-explanation effects (Chi, 2000)",
    type: "text-recall" as const,
  },
  {
    id: "interleaved-retrieval",
    domain: "recall",
    name: "Interleaved Retrieval",
    emoji: "🔀",
    difficulty: "Hard",
    durationMin: 8,
    description: "Mixed question sets from different categories in unpredictable order.",
    instructions: "Questions will jump between topics. Don't expect patterns — the unpredictability is the training. Respond quickly but accurately.",
    transferNote: "Interleaving forces category discrimination and strengthens retrieval even when cues are weak.",
    evidenceBasis: "Rohrer & Taylor (2007); interleaving effect in motor and cognitive learning",
    type: "mcq" as const,
  },

  // WORKING MEMORY
  {
    id: "n-back-real",
    domain: "working_memory",
    name: "Real-World N-Back",
    emoji: "⚡",
    difficulty: "Adaptive",
    durationMin: 5,
    description: "N-back task using realistic stimuli: patient details, medication names, instructions.",
    instructions: "A sequence of items will appear one at a time. Respond 'MATCH' if the current item matches the one N steps back. N increases as you improve.",
    transferNote: "Near-transfer to sustained attention and updating tasks. More ecologically valid than abstract shapes.",
    evidenceBasis: "Pahor et al., Nature Human Behaviour 2022; near-transfer mediation model",
    type: "n-back" as const,
  },
  {
    id: "span-tracking",
    domain: "working_memory",
    name: "Multi-Variable Tracker",
    emoji: "🔢",
    difficulty: "Medium",
    durationMin: 4,
    description: "Hold multiple changing values in mind simultaneously. Update as new information arrives.",
    instructions: "You'll see variables change in real time. Track them without writing anything down. At the end, report all current values.",
    transferNote: "Models the cognitive demand of tracking multiple patients, tasks, or variables under time pressure.",
    evidenceBasis: "Adaptive span tasks; central executive component of Baddeley's WM model",
    type: "span-track" as const,
  },

  // FOCUS
  {
    id: "stroop-advanced",
    domain: "focus",
    name: "Stroop Inhibition Task",
    emoji: "🎯",
    difficulty: "Adaptive",
    durationMin: 4,
    description: "Respond to the meaning, not the appearance. Suppresses automatic, habitual responses.",
    instructions: "Respond to the WORD MEANING (not the color of the text). Press the correct key as fast as possible. Accuracy matters more than speed.",
    transferNote: "Trains the inhibitory control system: suppressing dominant but incorrect responses.",
    evidenceBasis: "Stroop (1935); Miyake et al. (2000) executive function framework",
    type: "stroop" as const,
  },
  {
    id: "go-nogo",
    domain: "focus",
    name: "Go / No-Go",
    emoji: "🚦",
    difficulty: "Medium",
    durationMin: 3,
    description: "Respond fast to 'Go' targets. Withhold completely on 'No-Go' signals.",
    instructions: "Press SPACE when you see a GO stimulus. Do not press on NO-GO. The ratio of Go/No-Go shifts without warning to prevent prediction.",
    transferNote: "Core impulse control training. Transfers to resisting impulsive decisions, corrections, or premature actions.",
    evidenceBasis: "Aron & Poldrack (2006); right IFG inhibitory control circuit",
    type: "go-nogo" as const,
  },

  // FLEXIBILITY
  {
    id: "rule-shift",
    domain: "flexibility",
    name: "Rule Shift Challenge",
    emoji: "🔄",
    difficulty: "Hard",
    durationMin: 5,
    description: "Categorize stimuli by a rule — then the rule changes without warning.",
    instructions: "Sort cards by the current rule. When your responses start producing errors, the rule has changed. Detect it, adapt, continue.",
    transferNote: "Models the cognitive demand of adapting when standard protocols no longer apply.",
    evidenceBasis: "Wisconsin Card Sorting adaptation; task-switching research (Meiran, 1996)",
    type: "rule-shift" as const,
  },
  {
    id: "reframe-challenge",
    domain: "flexibility",
    name: "Forced Reframing",
    emoji: "🔁",
    difficulty: "Medium",
    durationMin: 4,
    description: "A problem or scenario is given. Generate as many reframings as possible in 60 seconds.",
    instructions: "You'll see a situation framed one way. Find 3 completely different ways to interpret it. Challenge your first assumption.",
    transferNote: "Builds perspective-shifting for handling ambiguous or unfamiliar situations.",
    evidenceBasis: "Cognitive reappraisal research; schema flexibility",
    type: "reframe" as const,
  },

  // PROBLEM SOLVING
  {
    id: "fermi-estimate",
    domain: "problem_solving",
    name: "Fermi Estimation",
    emoji: "🔧",
    difficulty: "Medium",
    durationMin: 4,
    description: "Estimate quantities you cannot look up, using first-principles reasoning.",
    instructions: "You'll receive a question with no obvious answer. Break it down from first principles. Show your reasoning. Then compare to the calibrated range.",
    transferNote: "Builds systematic decomposition of complex unknowns — a core clinical and strategic reasoning skill.",
    evidenceBasis: "Deliberate practice; first-principles reasoning; decomposition strategies",
    type: "fermi" as const,
  },
  {
    id: "root-cause",
    domain: "problem_solving",
    name: "Root Cause Analysis",
    emoji: "🌲",
    difficulty: "Hard",
    durationMin: 6,
    description: "A scenario presents a problem. Find the root cause, not just the symptom.",
    instructions: "Read the scenario carefully. Ask 'why' at least 3 levels deep. Identify the structural cause, not the surface symptom. Rate your confidence.",
    transferNote: "Mirrors clinical reasoning, engineering troubleshooting, and strategic diagnosis.",
    evidenceBasis: "5-Whys technique; causal reasoning in clinical education",
    type: "root-cause" as const,
  },

  // CREATIVITY
  {
    id: "constraint-solve",
    domain: "creativity",
    name: "Constraint Creativity",
    emoji: "💡",
    difficulty: "Medium",
    durationMin: 4,
    description: "Solve a real problem under unusual constraints that force novel approaches.",
    instructions: "You have a problem and unusual constraints. Generate solutions within the constraints. Don't break them — work through them.",
    transferNote: "Constraints paradoxically enhance creative output by forcing divergent pathways.",
    evidenceBasis: "Ward (1994) structured imagination; creativity constraint effects",
    type: "constraint-creative" as const,
  },
  {
    id: "analogy-builder",
    domain: "creativity",
    name: "Analogy Builder",
    emoji: "🔗",
    difficulty: "Easy",
    durationMin: 3,
    description: "Connect two unrelated concepts and explain how one illuminates the other.",
    instructions: "You'll receive two concepts from different domains. Find a meaningful analogy between them. Explain the mapping clearly.",
    transferNote: "Analogical reasoning is a core mechanism of creative insight and knowledge transfer between domains.",
    evidenceBasis: "Holyoak & Thagard (1995); analogical transfer in learning science",
    type: "analogy" as const,
  },

  // INTUITION
  {
    id: "calibration-drill",
    domain: "intuition",
    name: "Calibration Drill",
    emoji: "🔮",
    difficulty: "Medium",
    durationMin: 5,
    description: "Answer fast, rate your confidence, receive calibration feedback.",
    instructions: "For each question, answer quickly then rate your confidence (0-100%). After each batch, your calibration curve shows whether your confidence matches your accuracy.",
    transferNote: "Identifies overconfidence and underconfidence patterns. Critical for clinical judgment and high-stakes decisions.",
    evidenceBasis: "Metacognitive calibration training (Seth & Lau, 2018); Brier score feedback",
    type: "calibration" as const,
  },
  {
    id: "pattern-recognition",
    domain: "intuition",
    name: "Pattern Recognition",
    emoji: "🧩",
    difficulty: "Adaptive",
    durationMin: 4,
    description: "Identify the rule or pattern in a sequence. Fast and accurate.",
    instructions: "A sequence of items will appear. Identify the underlying pattern as quickly as possible. Rate how confident you are.",
    transferNote: "Builds the rapid-recognition system that underlies expert intuition in clinical, analytical, and strategic domains.",
    evidenceBasis: "Klein (1999) recognition-primed decision model; expertise research",
    type: "pattern" as const,
  },
];

// Quick scenario seeds
export const SCENARIOS = [
  {
    id: "emergency-triage",
    title: "Emergency Triage",
    domain: "problem_solving",
    emoji: "🏥",
    difficulty: "Hard",
    durationMin: 8,
    context: "MICU context: 3 patients deteriorate simultaneously at 2am.",
    description: "You have 4 patients. Three begin showing signs of change simultaneously. You have one nurse available to assist. Prioritize your actions for the next 15 minutes.",
    skills: ["recall", "working_memory", "problem_solving", "focus"],
    prompt: `A 52yo with sepsis begins desaturating to 88%. A 67yo post-CABG develops new ST-changes and diaphoresis. Your 38yo TBI patient becomes agitated and tries to pull their lines. The 4th patient is stable on ventilator support. You have one tech available. Rapid response is activated for someone else on the floor.\n\nUsing your clinical knowledge and prioritization skills:\n1. Who do you assess FIRST and why?\n2. What immediate interventions do you delegate?\n3. What information do you need to gather in the first 60 seconds?\n4. What is your communication plan?`,
  },
  {
    id: "day-planning",
    title: "Conflict Resolution",
    domain: "flexibility",
    emoji: "📅",
    difficulty: "Medium",
    durationMin: 5,
    context: "Professional context: your day falls apart in the first hour.",
    description: "You planned a key project. Three things go wrong simultaneously. Rebuild your day optimally.",
    skills: ["flexibility", "problem_solving", "working_memory"],
    prompt: `You planned today around completing a high-stakes report due at 5pm. It's 9am. Your main data source just went offline (ETA: unknown). A team member called in sick. And your manager just scheduled a 2-hour meeting at 1pm that wasn't on your calendar.\n\n1. List your revised priorities in order.\n2. What do you cut or delegate?\n3. What is your minimum viable plan to hit the 5pm deadline?\n4. What will you do if the data source isn't back by noon?`,
  },
  {
    id: "incomplete-data",
    title: "Decide With Incomplete Data",
    domain: "intuition",
    emoji: "🌫️",
    difficulty: "Hard",
    durationMin: 6,
    context: "Leadership context: the information you need doesn't exist yet.",
    description: "You must make a significant decision with only 60% of the information you need.",
    skills: ["intuition", "problem_solving", "metacognition"],
    prompt: `Your organization needs to decide whether to expand to a new market by end of month. Market research is incomplete. Competitive data is a year old. Two advisors give contradictory recommendations. The opportunity may close if you wait.\n\n1. What is your decision framework here?\n2. What is the minimum information you absolutely must have?\n3. What's the cost of a wrong decision in each direction?\n4. How confident are you right now, and why? What would move your confidence 20% in either direction?`,
  },
  {
    id: "communication-failure",
    title: "SBAR Communication Under Pressure",
    domain: "recall",
    emoji: "📞",
    difficulty: "Medium",
    durationMin: 5,
    context: "Clinical context: fast, accurate handoff under time pressure.",
    description: "Communicate a patient's change in condition clearly and completely in under 90 seconds using SBAR.",
    skills: ["recall", "working_memory", "metacognition"],
    prompt: `Your patient: 74yo F, admitted 3 days ago for community-acquired pneumonia. Stable yesterday. This morning: RR 28, SpO2 88% on 3L NC, temp 38.9°C, HR 112, BP 88/54. GCS 14 (down from 15). Last ABG 2 hours ago was normal. No recent changes in medications. You're calling the attending.\n\nConstruct a complete SBAR:\n- Situation: What is happening right now?\n- Background: Relevant history\n- Assessment: What do you think is happening?\n- Recommendation: What do you need?`,
  },
  {
    id: "creative-solve",
    title: "Invent Around a Constraint",
    domain: "creativity",
    emoji: "⚙️",
    difficulty: "Medium",
    durationMin: 6,
    context: "Innovation context: budget is gone, deadline isn't.",
    description: "Your project loses 80% of its budget at the midpoint. Find 5 ways to still deliver value.",
    skills: ["creativity", "flexibility", "problem_solving"],
    prompt: `You're leading a quality improvement project for discharge education. You had funding for printed materials, a dedicated educator, and tech infrastructure. All three are now unavailable. The hospital board still expects a presentation of your results in 6 weeks.\n\n1. What are 5 creative alternatives to your original plan?\n2. Which of those 5 would you actually pursue and why?\n3. What assumptions about "how things must be done" are you releasing?\n4. What is the minimum viable version of your original goal?`,
  },
];

export type ActivityType = typeof ACTIVITIES[0]["type"];
