-- ═══════════════════════════════════════════════════════════════════════════
-- ROME · Idea Workshop v2
--
-- Run once, in the Supabase dashboard → SQL Editor → New query → Run.
-- The repo has no migration runner (drizzle is vestigial, see CLAUDE.md), so
-- this file is the record of what the database looks like, not something the
-- app executes.
--
-- Idempotent: safe to run twice. Non-destructive: nothing is dropped, every
-- new column is nullable or carries a default, so the current build keeps
-- working before and after it runs.
--
-- What it does
--   1. Adds board_folders — the "cores" that replace the single hard-coded
--      Creative Core in the graph sidebar. One row per renamable file that
--      workshops are filed into.
--   2. Gives boards a folder_id. NULL means unfiled, which is what every
--      existing row becomes, so nothing has to be migrated by hand.
--   3. Teaches idea_cards three new things: what kind of card it is (text or
--      image), which card it hangs off (sub-ideas), and where an image lives.
--
-- No foreign keys on purpose. The two API twins already own referential
-- cleanup for boards and idea_connections, the id column types of the
-- existing tables are not guaranteed here, and a failed FK would abort the
-- whole script. Deleting a core nulls its boards; deleting a parent card
-- deletes its children — both in application code, in both twins.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

-- ── 1 · Cores ─────────────────────────────────────────────────────────────
--
-- Scoped by type as well as user: the graph sidebar is shared by the Idea
-- Workshop and the Component Board, and a core belongs to exactly one of them.

create table if not exists public.board_folders (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null,
  type       text   not null,
  name       text   not null default 'New Core',
  color      text   not null default 'cyan',
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists board_folders_user_type_idx
  on public.board_folders (user_id, type);

-- ── 2 · Filing ────────────────────────────────────────────────────────────
--
-- NULL is "unfiled", and the sidebar shows an Unfiled core for those rows
-- rather than hiding them, so a board can never become unreachable.

alter table public.boards
  add column if not exists folder_id bigint;

create index if not exists boards_folder_idx on public.boards (folder_id);

-- ── 3 · Cards ─────────────────────────────────────────────────────────────
--
-- kind splits the one card table rather than adding a second one: images and
-- text share position, size, colour, linking and sub-ideas, and every one of
-- those would have had to be written twice.
--
-- parent_id makes a card a sub-idea. A sub-idea's pos_x/pos_y are an OFFSET
-- from its parent's top-left, not canvas coordinates — that is what lets a
-- parent be dragged without touching a single child row.
--
-- src carries a data: URL for image cards. Kept out of content so that a card
-- converted between kinds does not lose its text.

alter table public.idea_cards
  add column if not exists kind text not null default 'text';

alter table public.idea_cards
  add column if not exists parent_id bigint;

alter table public.idea_cards
  add column if not exists src text;

create index if not exists idea_cards_parent_idx on public.idea_cards (parent_id);

-- align is a card-level property, not a property of a selection, so it lives on
-- the row rather than inside the content HTML. Centre is the default because a
-- card is a label far more often than it is a paragraph.

alter table public.idea_cards
  add column if not exists align text not null default 'center';

commit;
